name: kTriggers
main: net.krinsoft.ktriggers.TriggerPlugin
version: ${project.version}-${project.build.number} for Bukkit 1.2.3-R0.1
author: krinsdeath
load: startup

commands:
  ktrigger:
    description: Base command for triggering aliases
    usage: /<command>