name: kTriggers
main: net.krinsoft.ktriggers.TriggerPlugin
version: ${project.version}-${project.build.number}
author: krinsdeath
load: startup

commands:
  ktrigger:
    description: Base command for triggering aliases
    usage: /<command>